---
language: php

# Python instead of php?
# We need a way of having both php and python
php:
  - 5.6

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
 - sudo apt-get update -qq

  # Install Ansible dependencies
 - sudo apt-get install -qq python-apt python-pycurl

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  # Install Drush
  - composer global require drush/drush:dev-master
  - phpenv rehash

  # Create MySQL Database
  - mysql -e 'create database drupal;'

  # Download Drupal
  - cd ..
  - drush dl drupal-7 --drupal-project-rename=drupal
  - cd drupal

  # Install drupal default profile
  - drush --verbose site-install --db-url=mysql://root:@127.0.0.1/drupal --yes

  # Ansible
  - pip install ansible>=1.6.0

  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  # Prepare tests
  - echo localhost > inventory

  # Check syntax
  - ansible-playbook --syntax-check -i inventory test.yml

  # First run
  - ansible-playbook -e "drupal_user=root" -i inventory test.yml --connection=local --sudo

  # Idempotence
  - >
    ansible-playbook -e "drupal_user=root" -i inventory test.yml --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
